[build]
  base = "."
  publish = "api"
  command = "pip install -r requirements.txt && cd api && gunicorn app:app"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
  FLASK_ENV = "production"
  PORT = "8080"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"