[build]
  command = "docker build -t ai-leetcode-analyzer ."
  publish = "api"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
  FLASK_ENV = "production"

[context.production]
  command = "docker build -t ai-leetcode-analyzer ."

[context.deploy-preview]
  command = "docker build -t ai-leetcode-analyzer ."

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"