apiVersion: apps/v1
kind: Deployment
metadata:
  name: leetcode-analysis-api
  namespace: leetcode-analysis
  labels:
    app: leetcode-analysis-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leetcode-analysis-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: leetcode-analysis-api
    spec:
      containers:
      - name: api
        image: leetcode-analysis-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: leetcode-analysis-api-service
  namespace: leetcode-analysis
spec:
  selector:
    app: leetcode-analysis-api
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP